# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# http://docs.travis-ci.com

env:
  global:
    - secure: "UvlM++538EzR9rj/8rJQ8P8e/OfJ0CZVe/N7CS2N0tA0AqBJRH9ytNjlrVKB8/TQwqoZCfM42NWfMKnvZql6BYCs4h9v25rhDreAFMTh/WNCBLQogtfDxw3Vlj25I3qLqe5COv57ELyBgKI34ViWVW7lWBS2vQOX+D2pTIqZ6bo="

language: node_js

node_js:
  - "4"

sudo: false
