# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com

env:
  global:
    - secure: "H+HiCKmoXgkwdCX6H/IUiI191yWnNbv6TLsXmp8ywH/xmMiYyeDpTjEm3F3YdrJMkTrwchVF/CwyAaiI4lZi663RTHjBKYMWW0XYZoT5Lw54xldvMBrimhxNJMCs4iYLecaw36cYHn6BB+P9xk53ufeBg3OP5vc6eaB9T8IE22Y="

language: node_js

node_js:
  - "6"

sudo: false
